### ISSUE TITLE
widgets crash 

### ISSUE THREAD

**Issue by LowWebSite** [moonstonemedia/WP-Google-Calendar-Events#46]
We get this error when the page widgets crash. 

There is 2 google calendar feeds. Does not seem to be special to any browser. 

GCE_Display::get_event_days(): 
The script tried to execute a method or access a property of an incomplete object.

Please ensure that the class definition GCE_Event of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

**Comment by nekojira** [comment]
Hi @LowWebSite,  we are aware of this problem; it's an issue that seem to happen on Godaddy or some hosts that implement some object caching. It's likely due to the current status of the plugin architecture and its objects mapping. We are in the process of rewriting it from ground up (see refactor branch for an idea of the changes) that addresses this and other problems. If you have a patch for the current dev branch which can fix this quickly, you are very welcome to submit a pull request.

**Comment by LowWebSite** [comment]
That was quick, Thanks

I found this:
https://www.godaddy.com/help/installing-and-configuring-the-w3-total-cache-plugin-on-wordpress-7299
Would it help, in this case?

**Comment by nekojira** [comment]
try disabling object cache

**Comment by LowWebSite** [comment]
I'm sorry I was a little vague, we do not have the w3-total-cache plugin installed. So I take it, installing it will not help.

**Comment by nekojira** [comment]
perhaps can you look at the bottom of this thread: there are some advices https://wordpress.org/support/topic/fatal-error-on-homepage-1/page/3?replies=84
